# title: "Indiana Fever Schedule"
# description: "2025 Indiana Fever Schedule"
# logo: https://mccright.github.io/rrl/m.svg
# https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/setting-a-markdown-processor-for-your-github-pages-site-using-jekyll 
# theme: jekyll-theme-slate
markdown: GFM  